var language = {
    "en_us": {
        "GO_TO_DEAL": "Go to Shop >>",
        "SIMILAR_SHOPS": "Similar Shops To",
        "COUPONS": " Coupons",
        "COPIED": "Copied",
        "COPY": "Copy Code",
        "COPYLINK": "Copy",
        "OR": "OR", // %
        "VERIFIED": "",
        "WORKED": "Worked",
        "SUB_WORKED": "",
        "JUST_NOW": "just now",
        "HOURS": "hours",
        "HOUR": "hour",
        "DAYS": "days",
        "DAY": "day",
        "AGO": "ago",
        "MINUTES": "minutes",
        "USERS": "users",
        "CODES": " codes",
        "CODE": " code",
        "UP_TO": "Up to",
        "REWARDS": "rewards",
        "EMAIL_CORRECT_TIPS": "Email is not correct",
        "EMAIL_REGISTERED_TIPS": "This email address has already been registered.",
        "PASSWORD_ERROR_LENGTH_TIPS": "At least 6 characters",
        "PASSWORD_PLACEHODLER": "At least 6 characters",
        "LOGIN_ERROR_TIPS": "Incorrect email or password",
        "SEE_DEALS": "See Deal >",
        "EMAIL": "Email",
        "SEARCH_STORE": "Search Store",
        "FEEDBACK": "Your Feedback*",
        "FEEDBACK_EMAIL": "Email address*",
        "CASHBACK_ACTIVE": "Cashback Activated",
        "HOW_IT_WORKS": "<span class=\"noclick\">Get rewarded for stuff that you're already buying with Coupert Gold! Merchants give us a small commission for bringing them business, and we directly share it with you through our free Coupert Gold rewards program. And Coupert Gold will be added into your account automatically when we are informed about the transaction, but the action dose not take place in real time. Before placing your order, please confirm that Coupert is the only or last cash back program you have activated.</span><br><span class=\"canclick\">Learn more</span>",
        "CB_UNACTIVE_TEXT": "Activate <span class='__coupert-cashback-rate'>[CB_RATE]</span> CashBack",
        "CB_ACTIVE_TEXT": "<span class='__coupert-cashback-rate'>[CB_RATE]</span> CashBack Rewards Activated",
    },
    "fr": {
        "GO_TO_DEAL": "Allez vers cette boutique >>",
        "SIMILAR_SHOPS": "Boutique similaire &agrave;",
        "COUPONS": "Offres de ",
        "COPIED": "copi&eacute;",
        "COPY": "Copier Code",
        "COPYLINK": "Copier",
        "OR": "OU",
        "VERIFIED": "",
        "WORKED": "V&eacute;rifi&eacute;",
        "SUB_WORKED": " il y a",
        "JUST_NOW": "&agrave; l'instant",
        "HOURS": "heures",
        "HOUR": "heure",
        "DAYS": "jours",
        "DAY": "jour",
        "AGO": "",
        "MINUTES": "minutes",
        "USERS": "utilis&eacute;s",
        "CODES": " codes",
        "CODE": " code",
        "UP_TO": "Jusqu\'"+"&agrave;",
        "REWARDS": "bonus",
        "EMAIL_CORRECT_TIPS": "L'address e-mail n'est pas correct",
        "EMAIL_REGISTERED_TIPS": "Cette adresse e-mail a d&eacute;j&agrave; &eacute;t&eacute; enregistr&eacute;e.",
        "PASSWORD_ERROR_LENGTH_TIPS": "Au moins 6 caract" + '&eacute;' + "res",
        "PASSWORD_PLACEHODLER": "Mot de passe",
        "LOGIN_ERROR_TIPS": "E-mail ou mot de passe incorrect",
        "SEE_DEALS": "Voir l'offre >",
        "EMAIL": "Adresse e-mail",
        "SEARCH_STORE": "Rechercher",
        "FEEDBACK": "Votre avis*",
        "FEEDBACK_EMAIL": "Adresse e-mail*",
        "CASHBACK_ACTIVE": "Cashback activ&eacute;",
        "HOW_IT_WORKS": "<span class=\"noclick\">Soyez récompensé pour tout ce que vous achetez déjà avec Coupert Gold! Les commerçants nous donnent une petite commission pour leur apporter des affaires, et nous la partageons directement avec vous via notre programme gratuit de récompenses Coupert Gold. Et Coupert Gold sera automatiquement ajouté à votre compte lorsque nous serons informés de la transaction, mais l'action ne se déroulera pas en temps réel. Avant de passer votre commande, veuillez confirmer que Coupert est le seul ou le dernier programme de remise en argent que vous avez activé.</span><br><span class=\"canclick\">En savoir plus</span>",
        "CB_UNACTIVE_TEXT": "Activer <span class='__coupert-cashback-rate'>[CB_RATE]</span> CashBack",
        "CB_ACTIVE_TEXT": "<span class='__coupert-cashback-rate'>[CB_RATE]</span> CashBack Bonus Activés",
    },
    "pt": {
        "GO_TO_DEAL": "ir para a loja>>",
        "SIMILAR_SHOPS": "lojas semelhantes para",
        "COUPONS": " Cupons",
        "COPIED": "copiado",
        "COPY": "Copiar Cupom",
        "COPYLINK": "Copiar",
        "OR": "ou",
        "VERIFIED": "verificado",
        "WORKED": "funcionou",
        "SUB_WORKED": "",
        "JUST_NOW": "agora mesmo",
        "HOURS": "horas",
        "HOUR": "hora",
        "DAYS": "dias",
        "DAY": "dia",
        "AGO": "atr&aacute;s",
        "MINUTES": "minutos",
        "USERS": "usu&aacute;rios",
        "CODES": " c&oacute;digos",
        "CODE": " c&oacute;digo",
        "UP_TO": "at&eacute;",
        "REWARDS": "recompensas",
        "EMAIL_CORRECT_TIPS": "o email est&aacute; errado",
        "EMAIL_REGISTERED_TIPS": "Este endere&ccedil;o de email j&aacute; foi registrado.",
        "PASSWORD_ERROR_LENGTH_TIPS": "Pelo menos 6 carateres",
        "PASSWORD_PLACEHODLER": "Pelo menos 6 carateres",
        "LOGIN_ERROR_TIPS": "o email ou a senha errada",
        "SEE_DEALS": "veja a Promo&ccedil;&atilde;o",
        "EMAIL": "email",
        "SEARCH_STORE": "Pesquise lojas",
        "FEEDBACK": "O seu feedback",
        "FEEDBACK_EMAIL": "Endere%c3%a7o de email",
        "CASHBACK_ACTIVE": "Cashback ativado",
        "HOW_IT_WORKS": "<span class=\"noclick\">Seja recompensado por itens que você já está comprando com a Coupert Gold! Os comerciantes nos dão uma pequena comissão para gerar negócios e os compartilhamos diretamente com você através do nosso programa gratuito de recompensas Coupert Gold. E o Coupert Gold será adicionado à sua conta automaticamente quando formos informados sobre a transação, mas a dose da ação não ocorrerá em tempo real. Antes de fazer seu pedido, confirme se o Coupert é o único ou o último programa de devolução que você ativou.</span><br><span class=\"canclick\">Saiba mais</span>",
        "CB_UNACTIVE_TEXT": "Ativar <span class='__coupert-cashback-rate'>[CB_RATE]</span> CashBack",       
        "CB_ACTIVE_TEXT": "<span class='__coupert-cashback-rate'>[CB_RATE]</span> CashBack Recompensas Ativadas.",
    }
};